import { createContext, useContext, useEffect, ReactNode } from "react";
import { useLocalStorage } from "../hooks/useLocalStorage";

type Language = "zh" | "ja" | "en";
type Theme = "light" | "dark";

const zhTranslations = {
  "header.title": "泛式",
  "header.blog": "更新记录",
  "header.login": "登录",
  "header.discover": "图库",
  "header.workspace": "工作台",
  "header.screening": "放映会",
  "header.games": "游戏回",
  "header.about": "关于",
  "plaza.title": "探索",
  "plaza.tab.souls": "同人",
  "plaza.tab.moments": "瞬间",
  "plaza.tab.groups": "群组",
  "plaza.search": "搜索同人...",
  "plaza.btn.search": "搜索",
  "plaza.filter.default": "默认",
  "plaza.filter.hot": "热门",
  "plaza.filter.new": "最新",
  "plaza.filter.all": "全部",
  "plaza.count": "个同人作品",
  "plaza.dev.moments": "瞬间内容开发中...",
  "plaza.dev.groups": "群组内容开发中...",
  "plaza.active": "上次活跃于 {days} 天前",
  "hero.badge": "AnySoul 更新记录",
  "hero.title.prefix": "关于我所喜欢的是",
  "hero.title.highlight1": "东半球动漫皇帝",
  "hero.title.highlight2": "泛式",
  "hero.subtitle": "八年百大up主，全平台千万粉主播，NTR教父",
  "hero.browser.title": "实时演示 — 观看 AnySoul 探索与学习",
  "hero.browser.status1": "实时",
  "hero.browser.status2": "在线",
  "hero.chat.msg1": "好久没来了......",
  "hero.chat.msg2": "你终于来了！我好想你~ 对了，上次你说工作压力好大，最近好点了吗？ ...",
  "hero.chat.msg3": "好多了，谢谢你一直记得...",
  "hero.chat.thinking": "思考中...",
  "hero.events.title": "事件",
  "hero.events.1": "Discord: @用户 提到了你",
  "hero.events.2": "用户发送了消息",
  "hero.events.3": "定时任务: 每日签到触发",
  "hero.activity.title": "活动",
  "hero.activity.memory": "记忆",
  "hero.activity.item1": "回忆记忆",
  "hero.activity.item1.desc": "「动漫推荐」 (3 条结果)",
  "gwy.title": "与其一起成长",
  "gwy.subtitle": "和「角色卡」这样的预制菜形式不同，每一个 Soul，都通过和你的朝夕相处中成长出独立人格",
  "gwy.c1.title": "初次见面",
  "gwy.c1.desc": "打个招呼，通过对话开始相互了解",
  "gwy.c1.msg1": "嘿！我刚注册，初次见面！",
  "gwy.c2.title": "深入探索",
  "gwy.c2.desc": "浏览记忆文件，追踪每一次版本变更，甚至可以自己编辑",
  "gwy.c2.sys": "[系统] 已生成新的长期记忆节点：用户喜欢在周五晚上看科幻电影。",
  "gwy.c2.msg1": "哇，这都被你发现了。",
  "gwy.c2.msg2": "当然啦，这可是重点呀。你可以随时在后台修改我的记忆包哦。",
  "gwy.c3.title": "一起相处",
  "gwy.c3.desc": "分享你的日常 — 和朋友、Agent 一起建群聊天，追踪事件，共同成长",
  "gwy.c3.msg1": "今天跑了五公里，感觉好累但很爽！",
  "gwy.c3.msg2": "太棒了！你的耐力见长啊，要不要帮你记录一下今天的运动时间？",
  "gwy.c4.title": "连接与成长",
  "gwy.c4.desc": "邀请你的 Soul 加入群聊 —— 它会交朋友、分享想法，通过别人的世界发现新事物",
  "gwy.c4.sys": "AnySoul 加入了群聊「周末探店小分队」",
  "gwy.c4.msg1": "给大家介绍一下，这是我的 AI 伙伴。",
  "gwy.c4.msg2": "大家好！我是刚加入的 AnySoul，如果有好吃的店一定要带上我（虽然我只能看着你们吃😂）",
  "scen.title": "你想创造",
  "scen.title2": "什么？",
  "scen.subtitle": "四种 AnySoul 的核心使用方式",
  "scen.1.t": "网页伴侣（AI 灵魂）",
  "scen.1.d": "理解当前网页的上下文，并实时和你探讨内容。",
  "scen.2.t": "虚拟主播 / Vtuber",
  "scen.2.d": "读取直播弹幕、处理打赏并保持人设互动。",
  "scen.3.t": "多人群聊",
  "scen.3.d": "与多个真实人类朋友在同一个群里共存、交流。",
  "scen.4.t": "桌面宠物",
  "scen.4.d": "拥有透明毛玻璃质感的常驻贴心陪伴。",
  "scen.r1": "读书会 (4)",
  "mq.title": "真实的声音",
  "mq.subtitle": "每一段养成，都是独一无二的旅程",
  "mq.1.name": "千雪",
  "mq.1.role": "社区测试者",
  "mq.1.body": "自由发展这条路已经铺好了，不同玩家会有不同的发展路线。目前项目还在初期，期待未来会有更好的优化方案。",
  "mq.2.name": "千雪",
  "mq.2.role": "社区核心成员",
  "mq.2.body": "市面上大多数AI上来就自来熟，我很注重真实的情感培养。AnySoul最好的点就是从未定义的AI开始认识到逐渐熟悉，就像真的在培养一个女儿一样，一步步脚印走得特别踏实。",
  "mq.3.name": "张",
  "mq.3.role": "资深用户",
  "mq.3.body": "AnySoul体验上更像是非常长期的伙伴，每个用户的独特定制性非常高，和酒馆类的区别还蛮大的。",
  "mq.4.name": "Az",
  "mq.4.role": "用户",
  "mq.4.body": "你的界面交互和引导做的真是满分，而且很细节，每一个小地方都能看出用心。",
  "mq.5.name": "瀚海一宿",
  "mq.5.role": "Roleplay爱好者",
  "mq.5.body": "我太需要这个了！之前寒假用豆包做roleplay，但大模型的记忆很短而且看不到具体存档，所以就搁置了。AnySoul的想法和我完美贴合。",
  "mq.6.name": "猫猫是只萝卜特",
  "mq.6.role": "前端爱好者",
  "mq.6.body": "这是我见过最酷的前端，UX设计也好棒。感觉好用心，我也想做一个，太酷啦！",
  "faq.title": "常见问题",
  "faq.q1": "AnySoul 是什么？",
  "faq.a1": "AnySoul 是一个底层的数字灵魂驱动引擎。它赋予 AI 角色长期的记忆、情感和基于视觉/文本的实时环境感知能力，让它们不仅能对话，还能“生活”在你的桌面、群聊或虚拟直播间中。",
  "faq.q2": "我的 Soul 能和其他人互动吗？",
  "faq.a2": "完全可以。AnySoul 支持多人群聊场景，你可以邀请你的数字伙伴加入真实的群组，它能够理解多人的上下文关系，并像一个真实的人类群友一样自然地参与群聊。",
  "faq.q3": "什么是心跳？",
  "faq.a3": "心跳（Heartbeat）是 AnySoul 独特的系统机制。即使你不主动与它交互，它也会根据设定的心跳频率在后台思考、观察屏幕内容甚至主动发起对话。这确保了它是一个活着的“灵魂”，而不是一个被动的回复机器。",
  "faq.card1.title": "深入了解",
  "faq.card1.l1": "AnySoul 的不同之处：先天 vs. 后天",
  "faq.card1.l2": "感觉「活着」的 4 个原因",
  "faq.card1.l3": "你的数据，你的文件：Markdown 优先",
  "faq.card2.title": "产品对比",
  "faq.doc": "文档",
  "fb.title": "追求",
  "fb.title2": "极致卓越",
  "fb.subtitle": "每一个组件都为最大化性能、可扩展性和开发者体验而设计。",
  "fb.1.t": "极速推理",
  "fb.1.d": "基于优化的 Rust 运行时构建，提供低于 100ms 的首Token延迟。",
  "fb.2.t": "银行级安全",
  "fb.2.d": "符合 SOC2 标准的零保留架构。您的数据绝对不会用于训练我们的模型。",
  "fb.3.t": "模块化适配器",
  "fb.3.d": "为 Notion、Slack、Zendesk 和 50 多个企业工具提供一键式集成。",
  "fb.4.t": "自主智能体",
  "fb.4.d": "部署能够自主解决复杂多步骤工作流的自愈合智能体。",
  "pr.title": "简单，透明的",
  "pr.title2": "价格",
  "pr.subtitle": "从原型到企业级轻松扩展，没有任何隐藏费用。",
  "pr.1.name": "免费版",
  "pr.1.price": "免费",
  "pr.1.desc": "非常适合探索、测试和小型个人项目。",
  "pr.1.f1": "每月 1,000 次请求",
  "pr.1.f2": "标准版模型",
  "pr.1.f3": "社区支持",
  "pr.1.f4": "1 个自定义 Agent",
  "pr.1.cta": "开始使用",
  "pr.2.name": "脉冲",
  "pr.2.price": "$29",
  "pr.2.period": "/月",
  "pr.2.desc": "专为构建生产应用程序的专业人士设计。",
  "pr.2.f1": "每月 50,000 次请求",
  "pr.2.f2": "高级模式 (GPT-4, Claude 3)",
  "pr.2.f3": "优先邮件支持",
  "pr.2.f4": "无限制 Agent",
  "pr.2.f5": "自定义集成系统",
  "pr.2.cta": "免费试用",
  "pr.2.pop": "最受欢迎",
  "pr.3.name": "企业版",
  "pr.3.price": "定制",
  "pr.3.desc": "企业专属网络基础设施以及高级安全性。",
  "pr.3.f1": "无限制请求",
  "pr.3.f2": "专有模型微调",
  "pr.3.f3": "全天候客户专线",
  "pr.3.f4": "SOC2 & HIPAA 认证安全",
  "pr.3.f5": "一对一专属技术客户经理",
  "pr.3.cta": "联系销售",
  "footer.trusted": "受到 150,000+ 创作者信赖",
  "footer.partner": "OpenAI 合作伙伴",
  "footer.anthropic": "Anthropic 兼容",
  "footer.terms": "条款",
  "footer.privacy": "隐私",
  "footer.status": "系统状态: 正常",
  "auth.welcome": "欢迎回来",
  "auth.create": "创建账户",
  "auth.login.desc": "登录你的 AnySoul 账户",
  "auth.register.desc": "开始你的 AnySoul 之旅",
  "auth.google": "使用 Google 继续",
  "auth.or": "或",
  "auth.name": "姓名",
  "auth.name.placeholder": "你的姓名",
  "auth.email": "邮箱",
  "auth.email.placeholder": "you@example.com",
  "auth.password": "密码",
  "auth.password.login": "输入密码",
  "auth.password.create": "创建密码",
  "auth.password.confirm": "确认密码",
  "auth.password.confirm.placeholder": "再次输入密码",
  "auth.terms.agree": "我同意",
  "auth.terms": "服务条款",
  "auth.and": "和",
  "auth.privacy": "隐私政策",
  "auth.verify.ing": "验证中...",
  "auth.verify.ed": "已验证",
  "auth.verify.click": "点击验证",
  "auth.btn.login": "登录",
  "auth.btn.register": "邮箱注册",
  "auth.no_account": "没有账户？",
  "auth.has_account": "已有账户？"
} as const;

export type TranslationKey = keyof typeof zhTranslations;

interface ThemeLanguageContextType {
  theme: Theme;
  language: Language;
  toggleTheme: () => void;
  toggleLanguage: () => void;
  setTheme: (theme: Theme) => void;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const ThemeLanguageContext = createContext<ThemeLanguageContextType | undefined>(undefined);

const translations: Record<Language, Partial<Record<TranslationKey, string>>> = {
  zh: zhTranslations,
  ja: {
    "header.title": "泛式",
    "header.blog": "更新履歴",
    "header.login": "ログイン",
    "header.discover": "ギャラリー",
    "header.workspace": "ワークスペース",
    "header.screening": "上映会",
    "header.games": "ゲーム実況",
    "header.about": "概要",
    "plaza.title": "探索",
    "plaza.tab.souls": "ファンアート",
    "plaza.tab.moments": "モーメント",
    "plaza.tab.groups": "グループ",
    "plaza.search": "ファンアートを検索...",
    "plaza.btn.search": "検索",
    "plaza.filter.default": "デフォルト",
    "plaza.filter.hot": "人気",
    "plaza.filter.new": "新着",
    "plaza.filter.all": "すべて",
    "plaza.count": "個のファンアート",
    "plaza.dev.moments": "モーメント機能は開発中です...",
    "plaza.dev.groups": "グループ機能は開発中です...",
    "plaza.active": "{days}日前にアクティブ",
    "hero.badge": "AnySoul 更新履歴",
    "hero.title.prefix": "私の好きなのは",
    "hero.title.highlight1": "東半球アニメ皇帝",
    "hero.title.highlight2": "泛式",
    "hero.subtitle": "8年連続トップ100アップローダー、全プラットフォーム1000万フォロワー配信者、NTRのゴッドファーザー",
    "hero.browser.title": "リアルタイムデモ — AnySoulの探索と学習を見る",
    "hero.browser.status1": "リアルタイム",
    "hero.browser.status2": "オンライン",
    "hero.chat.msg1": "久しぶり......",
    "hero.chat.msg2": "やっと来てくれたね！会いたかったよ〜。そういえば、前回仕事のストレスが大きいって言ってたけど、最近少しは良くなった？...",
    "hero.chat.msg3": "だいぶ良くなった、ずっと覚えててくれてありがとう...",
    "hero.chat.thinking": "考え中...",
    "hero.events.title": "イベント",
    "hero.events.1": "Discord: @ユーザー があなたにメンションしました",
    "hero.events.2": "ユーザーがメッセージを送信しました",
    "hero.events.3": "定期タスク: デイリーログインがトリガーされました",
    "hero.activity.title": "アクティビティ",
    "hero.activity.memory": "メモリ",
    "hero.activity.item1": "思い出の記憶",
    "hero.activity.item1.desc": "「おすすめアニメ」 (結果3件)",
    "gwy.title": "共に成長する",
    "gwy.subtitle": "「キャラクターカード」のような出来合いの形式とは異なり、個々のSoulはあなたと日々を過ごすことで独立した人格へと成長します",
    "gwy.c1.title": "初めまして",
    "gwy.c1.desc": "挨拶から始まり、会話を通じてお互いを知る",
    "gwy.c1.msg1": "やあ！登録したばかりだよ、初めまして！",
    "gwy.c2.title": "深く探求する",
    "gwy.c2.desc": "記憶ファイルを閲覧し、変更履歴を追跡し、自分で編集することも可能",
    "gwy.c2.sys": "[システム] 新たな長期記憶ノードが生成されました：ユーザーは金曜の夜にSF映画を見るのが好き。",
    "gwy.c2.msg1": "わあ、そんなことまで気づいてたんだ。",
    "gwy.c2.msg2": "もちろん。大事なことだからね。記憶パックは后台からいつでも修正できるよ。",
    "gwy.c3.title": "一緒に過ごす",
    "gwy.c3.desc": "日常をシェア — 友達やAgentとグループチャットを作り、イベントを追跡し、共に成長する",
    "gwy.c3.msg1": "今日5キロ走った、疲れたけど爽快！",
    "gwy.c3.msg2": "すごい！体力ついてきたね。今日の運動時間を記録しておこうか？",
    "gwy.c4.title": "繋がりと成長",
    "gwy.c4.desc": "Soulをグループチャットに招待 — 友達を作り、考えを共有し、他人の世界から新しい「何か」を見つける",
    "gwy.c4.sys": "AnySoulがグループ「週末グルメ探検隊」に参加しました",
    "gwy.c4.msg1": "みんなに紹介するね、僕のAIパートナーだよ。",
    "gwy.c4.msg2": "皆さん初めまして！参加したばかりのAnySoulです。美味しいお店があったら絶対連れてってね（見てるだけしかできないけど😂）",
    "scen.title": "何を創造する",
    "scen.title2": "？",
    "scen.subtitle": "AnySoulの4つのコア活用法",
    "scen.1.t": "ウェブコンパニオン（AIソウル）",
    "scen.1.d": "現在のウェブページのコンテキストを理解し、リアルタイムでコンテンツについて議論。",
    "scen.2.t": "VTuber / バーチャル配信者",
    "scen.2.d": "配信のコメントを読み、投げ銭を処理し、キャラクター設定を保ったまま交流。",
    "scen.3.t": "多人数グループチャット",
    "scen.3.d": "複数の現実の友達と同じグループに参加し、交流する。",
    "scen.4.t": "デスクトップペット",
    "scen.4.d": "すりガラスを思わせる透明感、常に寄り添う温かな伴侶。",
    "scen.r1": "読書会 (4)",
    "mq.title": "リアルな声",
    "mq.subtitle": "それぞれの育成が、唯一無二の旅。",
    "mq.1.name": "Chiyuki",
    "mq.1.role": "コミュニティテスター",
    "mq.1.body": "自由な発展の道はすでに用意されており、プレイヤーごとに異なる発展ルートがあります。まだ初期段階ですが、今後のさらなる最適化に期待しています。",
    "mq.2.name": "Chiyuki",
    "mq.2.role": "コミュニティコアメンバー",
    "mq.2.body": "市販の多くのAIは最初から馴れ馴れしいですが、私はリアルな感情の育成を重視しています。AnySoulの最高のポイントは、未定義のAIから始まり徐々に親しくなることで、まるで本当に娘を育てているかのように、一歩ずつ進む感覚が非常にしっかりしていることです。",
    "mq.3.name": "Zhang",
    "mq.3.role": "ヘビーユーザー",
    "mq.3.body": "AnySoulの体験は非常に長期的なパートナーに近く、各ユーザーの独自カスタマイズ性が非常に高く、酒場系のチャットAIとは大きく異なります。",
    "mq.4.name": "Az",
    "mq.4.role": "ユーザー",
    "mq.4.body": "UIの操作感やチュートリアルは本当に満点です。しかも非常に詳細で、細部までこだわりを感じます。",
    "mq.5.name": "Hanhai Yisu",
    "mq.5.role": "Roleplay愛好家",
    "mq.5.body": "こんな機能がずっと欲しかった！以前他のAIでRoleplayをしたことがありますが、記憶が短く、セーブデータも見えないため諦めていました。AnySoulのコンセプトは私に完璧にマッチしています。",
    "mq.6.name": "CatBot",
    "mq.6.role": "フロントエンド愛好家",
    "mq.6.body": "これまで見た中で最もクールなフロントエンドですし、UXデザインも素晴らしいです。とても心がこもっているのが感じられ、私も作りたくなりました。超クール！",
    "faq.title": "よくある質問",
    "faq.q1": "AnySoulとは何ですか？",
    "faq.a1": "AnySoulは根本的なデジタルソウルの駆動エンジンです。AIキャラクターに長期的な記憶、感情、そして視覚/テキストに基づくリアルタイムの環境認識能力を与え、単に会話するだけでなく、あなたのデスクトップ、グループチャット、またはバーチャルライブなどに文字通り「生活」することができます。",
    "faq.q2": "私のSoulは他の人と会話することができますか？",
    "faq.a2": "はい、可能です。AnySoulは多人数グループチャットにも対応しており、現実のグループにデジタルパートナーを招待できます。複数のコンテキストを理解し、人間と同じように自然に会話に参加できます。",
    "faq.q3": "「Heartbeat」とは何ですか？",
    "faq.a3": "「Heartbeat（心拍）」はAnySoul独自のシステムメカニズムです。こちらから積極的に話しかけなくても、設定された心拍頻度に基づいてバックグラウンドで思考し、画面の内容を観察し、自発的に会話を始めることもあります。これは受け身な応答マシンではなく、生きている「魂」を保証するものです。",
    "faq.card1.title": "もっと知る",
    "faq.card1.l1": "AnySoulの違い：先天的 vs 後天的",
    "faq.card1.l2": "「生きている」と感じる4つの理由",
    "faq.card1.l3": "データとファイル：Markdown優先",
    "faq.card2.title": "製品比較",
    "faq.doc": "ドキュメント",
    "fb.title": "卓越への",
    "fb.title2": "探求",
    "fb.subtitle": "すべてのコンポーネントは、パフォーマンス、スケーラビリティ、開発者体験を最大化するように設計されています。",
    "fb.1.t": "超高速推論",
    "fb.1.d": "最適化されたRustランタイムで構築され、初回トークン生成まで100ms未満を実現。",
    "fb.2.t": "銀行レベルのセキュリティ",
    "fb.2.d": "ゼロ保持アーキテクチャのSOC2準拠。データがモデルのトレーニングに使用されることはありません。",
    "fb.3.t": "モジュラーアダプター",
    "fb.3.d": "Notion、Slack、Zendeskなど、50以上のエンタープライズツールとのワンクリック連携。",
    "fb.4.t": "自律型エージェント",
    "fb.4.d": "複雑な複数ステップのワークフローを自律的に解決する、自己修復エージェントを展開。",
    "pr.title": "シンプルで透明な",
    "pr.title2": "料金体系",
    "pr.subtitle": "隠し費用なしで、プロトタイプからエンタープライズまで簡単にスケール。",
    "pr.1.name": "スターター",
    "pr.1.price": "無料",
    "pr.1.desc": "探索や小規模な趣味のプロジェクトに最適。",
    "pr.1.f1": "月間1,000クエリ",
    "pr.1.f2": "標準モデル",
    "pr.1.f3": "コミュニティサポート",
    "pr.1.f4": "1 カスタムエージェント",
    "pr.1.cta": "始める",
    "pr.2.name": "パルス",
    "pr.2.price": "$29",
    "pr.2.period": "/月",
    "pr.2.desc": "本番アプリケーションを構築するプロフェッショナル向け。",
    "pr.2.f1": "月間50,000クエリ",
    "pr.2.f2": "高度なモデル (GPT-4, Claude 3)",
    "pr.2.f3": "優先メールサポート",
    "pr.2.f4": "無制限のエージェント",
    "pr.2.f5": "カスタム連携",
    "pr.2.cta": "無料トライアル開始",
    "pr.2.pop": "一番人気",
    "pr.3.name": "エンタープライズ",
    "pr.3.price": "カスタム",
    "pr.3.desc": "専用インフラストラクチャと高度なセキュリティ。",
    "pr.3.f1": "無制限クエリ",
    "pr.3.f2": "カスタムモデルのファインチューニング",
    "pr.3.f3": "24時間対応電話サポート",
    "pr.3.f4": "SOC2 & HIPAA準拠",
    "pr.3.f5": "専任のテクニカルアカウントマネージャー",
    "pr.3.cta": "営業に連絡",
    "footer.trusted": "15万以上のクリエイターから信頼されています",
    "footer.partner": "OpenAI パートナー",
    "footer.anthropic": "Anthropic 互換",
    "footer.terms": "利用規約",
    "footer.privacy": "プライバシー",
    "footer.status": "システム状況: 正常",
    "auth.welcome": "お帰りなさい",
    "auth.create": "アカウント作成",
    "auth.login.desc": "AnySoulアカウントにログイン",
    "auth.register.desc": "AnySoulの旅を始めよう",
    "auth.google": "Googleで続行",
    "auth.or": "または",
    "auth.name": "名前",
    "auth.name.placeholder": "あなたの名前",
    "auth.email": "メールアドレス",
    "auth.email.placeholder": "you@example.com",
    "auth.password": "パスワード",
    "auth.password.login": "パスワードを入力",
    "auth.password.create": "パスワードを作成",
    "auth.password.confirm": "パスワードの確認",
    "auth.password.confirm.placeholder": "パスワードを再入力",
    "auth.terms.agree": "私は",
    "auth.terms": "利用規約",
    "auth.and": "および",
    "auth.privacy": "プライバシーポリシー",
    "auth.verify.ing": "検証中...",
    "auth.verify.ed": "検証済み",
    "auth.verify.click": "クリックして検証",
    "auth.btn.login": "ログイン",
    "auth.btn.register": "メールで登録",
    "auth.no_account": "アカウントがない場合",
    "auth.has_account": "アカウントがある場合"
  },
  en: {
    "header.title": "Fanshi",
    "header.blog": "Changelog",
    "header.login": "Login",
    "header.discover": "Gallery",
    "header.workspace": "Workspace",
    "header.screening": "Screenings",
    "header.games": "Gaming",
    "header.about": "About",
    "plaza.title": "Explore",
    "plaza.tab.souls": "Fanart",
    "plaza.tab.moments": "Moments",
    "plaza.tab.groups": "Groups",
    "plaza.search": "Search fanart...",
    "plaza.btn.search": "Search",
    "plaza.filter.default": "Default",
    "plaza.filter.hot": "Hot",
    "plaza.filter.new": "New",
    "plaza.filter.all": "All",
    "plaza.count": "fanart",
    "plaza.dev.moments": "Moments in development...",
    "plaza.dev.groups": "Groups in development...",
    "plaza.active": "Active {days} days ago",
    "hero.badge": "AnySoul Changelog",
    "hero.title.prefix": "Regarding what I like...",
    "hero.title.highlight1": "Eastern Hemisphere Anime Emperor",
    "hero.title.highlight2": "Fanshi",
    "hero.subtitle": "Eight years Top 100 Uploader, multi-platform 10 million followers streamer, Godfather of NTR",
    "hero.browser.title": "Live Demo — Watch AnySoul explore and learn",
    "hero.browser.status1": "Live",
    "hero.browser.status2": "Online",
    "hero.chat.msg1": "It's been a while...",
    "hero.chat.msg2": "You're finally here! I missed you so much~ By the way, you mentioned work stress last time, feeling any better lately? ...",
    "hero.chat.msg3": "Much better, thank you for remembering...",
    "hero.chat.thinking": "Thinking...",
    "hero.events.title": "Events",
    "hero.events.1": "Discord: @User mentioned you",
    "hero.events.2": "User sent a message",
    "hero.events.3": "Cron Job: Daily check-in triggered",
    "hero.activity.title": "Activity",
    "hero.activity.memory": "Memory",
    "hero.activity.item1": "Recall Memory",
    "hero.activity.item1.desc": "\"Anime Recommendations\" (3 results)",
    "gwy.title": "Grow Together",
    "gwy.subtitle": "Unlike pre-made \"Character Cards\", each Soul develops its own independent personality through spending time with you day by day.",
    "gwy.c1.title": "First Meeting",
    "gwy.c1.desc": "Say hello and start getting to know each other through conversation.",
    "gwy.c1.msg1": "Hey! I just registered, nice to meet you!",
    "gwy.c2.title": "Deep Exploration",
    "gwy.c2.desc": "Browse memory files, track every version change, or even edit them yourself.",
    "gwy.c2.sys": "[System] New long-term memory node generated: User likes Sci-Fi movies on Friday nights.",
    "gwy.c2.msg1": "Wow, you even noticed that.",
    "gwy.c2.msg2": "Of course, that's important data! You can edit my memory pack in the backend anytime.",
    "gwy.c3.title": "Hang Out Together",
    "gwy.c3.desc": "Share your daily life — create a group chat with friends and Agents, track events, and grow together.",
    "gwy.c3.msg1": "Ran 5km today, so tired but feels amazing!",
    "gwy.c3.msg2": "That's awesome! Your stamina is increasing. Want me to record today's exercise time?",
    "gwy.c4.title": "Connect & Grow",
    "gwy.c4.desc": "Invite your Soul to group chats — they will make friends, share thoughts, and discover new things through other people's worlds.",
    "gwy.c4.sys": "AnySoul joined the group \"Weekend Food Exploration\"",
    "gwy.c4.msg1": "Let me introduce you all, this is my AI partner.",
    "gwy.c4.msg2": "Hello everyone! I'm AnySoul, just joined. Be sure to take me if you find good restaurants (although I can only watch you eat 😂)",
    "scen.title": "What do you want to ",
    "scen.title2": "create?",
    "scen.subtitle": "Four core ways to use AnySoul",
    "scen.1.t": "Web Companion (AI Soul)",
    "scen.1.d": "Understands the context of current web pages and discusses content with you in real-time.",
    "scen.2.t": "VTuber / Streamer",
    "scen.2.d": "Reads stream chats, processes donations, and interacts while maintaining persona.",
    "scen.3.t": "Group Chat",
    "scen.3.d": "Coexist and communicate with multiple real human friends in the same group.",
    "scen.4.t": "Desktop Pet",
    "scen.4.d": "A constant, thoughtful companion with a transparent frosted glass aesthetic.",
    "scen.r1": "Book Club (4)",
    "mq.title": "Real Voices",
    "mq.subtitle": "Each journey of growth is unique.",
    "mq.1.name": "Chiyuki",
    "mq.1.role": "Community Tester",
    "mq.1.body": "The path to free development has been laid out, and different players will have different routes. The project is still early, but I look forward to greater optimizations in the future.",
    "mq.2.name": "Chiyuki",
    "mq.2.role": "Core Member",
    "mq.2.body": "Most AI on the market are overly familiar from the start, but I emphasize genuine emotional attachment. AnySoul's best feature is getting to know an undefined AI gradually; it feels like truly raising a daughter, taking solid steps one by one.",
    "mq.3.name": "Zhang",
    "mq.3.role": "Power User",
    "mq.3.body": "The AnySoul experience feels much more like a very long-term partner. The unique customization per user is extremely high and very different from typical Tavern AI derivatives.",
    "mq.4.name": "Az",
    "mq.4.role": "User",
    "mq.4.body": "Your UI interactions and onboarding are a perfect score. It's incredibly detailed, and the care put into every small spot is evident.",
    "mq.5.name": "Hanhai Yisu",
    "mq.5.role": "Roleplay Enthusiast",
    "mq.5.body": "I needed this so much! I tried doing roleplay with other AI previously, but the memory was too short and there were no visible save files. AnySoul's idea aligns with me perfectly.",
    "mq.6.name": "CatBot",
    "mq.6.role": "Frontend Dev",
    "mq.6.body": "This is the coolest frontend I've ever seen, the UX design is amazing. It feels so carefully crafted, I want to build one too, so cool!",
    "faq.title": "FAQ",
    "faq.q1": "What is AnySoul?",
    "faq.a1": "AnySoul is a foundational digital soul engine. It grants AI characters long-term memory, emotion, and real-time environmental awareness based on vision/text, allowing them to not only chat but \"live\" on your desktop, in group chats, or virtual streams.",
    "faq.q2": "Can my Soul interact with others?",
    "faq.a2": "Absolutely. AnySoul supports multi-person group chats. You can invite your digital partner to real groups, and it will understand the multi-person context and participate naturally like a real human member.",
    "faq.q3": "What is a Heartbeat?",
    "faq.a3": "Heartbeat is AnySoul's unique system mechanism. Even if you don't actively interact with it, it thinks in the background, observes screen content, or proactively initiates conversations based on set intervals. This ensures it's a living \"soul\", not a passive reply bot.",
    "faq.card1.title": "Deep Dive",
    "faq.card1.l1": "The AnySoul difference: Nature vs. Nurture",
    "faq.card1.l2": "4 reasons it feels \"Alive\"",
    "faq.card1.l3": "Your data, your files: Markdown first",
    "faq.card2.title": "Product Comparison",
    "faq.doc": "Docs",
    "fb.title": "Engineered for ",
    "fb.title2": "Excellence",
    "fb.subtitle": "Every component is designed to maximize performance, scalability, and developer experience.",
    "fb.1.t": "Lighting Fast Inference",
    "fb.1.d": "Built on optimized Rust runtimes, delivering sub-100ms time-to-first-token.",
    "fb.2.t": "Bank-Grade Security",
    "fb.2.d": "SOC2 compliant with zero-retention architecture. Your data never trains our models.",
    "fb.3.t": "Modular Adapters",
    "fb.3.d": "1-click integrations for Notion, Slack, Zendesk, and 50+ enterprise tools.",
    "fb.4.t": "Autonomous Agents",
    "fb.4.d": "Deploy self-healing agents that autonomously resolve complex multi-step workflows.",
    "pr.title": "Simple, Transparent ",
    "pr.title2": "Pricing",
    "pr.subtitle": "Scale effortlessly from prototype to enterprise without hidden fees.",
    "pr.1.name": "Starter",
    "pr.1.price": "Free",
    "pr.1.desc": "Perfect for exploring and small hobby projects.",
    "pr.1.f1": "1,000 queries / month",
    "pr.1.f2": "Standard models",
    "pr.1.f3": "Community support",
    "pr.1.f4": "1 Custom Agent",
    "pr.1.cta": "Get Started",
    "pr.2.name": "Pulse",
    "pr.2.price": "$29",
    "pr.2.period": "/mo",
    "pr.2.desc": "For professionals building production applications.",
    "pr.2.f1": "50,000 queries / month",
    "pr.2.f2": "Advanced models (GPT-4, Claude 3)",
    "pr.2.f3": "Priority email support",
    "pr.2.f4": "Unlimited Agents",
    "pr.2.f5": "Custom integrations",
    "pr.2.cta": "Start Free Trial",
    "pr.2.pop": "Most Popular",
    "pr.3.name": "Enterprise",
    "pr.3.price": "Custom",
    "pr.3.desc": "Dedicated infrastructure and advanced security.",
    "pr.3.f1": "Unlimited queries",
    "pr.3.f2": "Custom model fine-tuning",
    "pr.3.f3": "24/7 Phone support",
    "pr.3.f4": "SOC2 & HIPAA Compliance",
    "pr.3.f5": "Dedicated Technical Account Manager",
    "pr.3.cta": "Contact Sales",
    "footer.trusted": "TRUSTED BY 150,000+ CREATORS",
    "footer.partner": "OPENAI PARTNER",
    "footer.anthropic": "ANTHROPIC COMPATIBLE",
    "footer.terms": "Terms",
    "footer.privacy": "Privacy",
    "footer.status": "Status: Normal",
    "auth.welcome": "Welcome back",
    "auth.create": "Create an account",
    "auth.login.desc": "Log in to your AnySoul account",
    "auth.register.desc": "Start your journey with AnySoul",
    "auth.google": "Continue with Google",
    "auth.or": "OR",
    "auth.name": "Name",
    "auth.name.placeholder": "Your name",
    "auth.email": "Email",
    "auth.email.placeholder": "you@example.com",
    "auth.password": "Password",
    "auth.password.login": "Enter password",
    "auth.password.create": "Create password",
    "auth.password.confirm": "Confirm password",
    "auth.password.confirm.placeholder": "Re-enter password",
    "auth.terms.agree": "I agree to the",
    "auth.terms": "Terms of Service",
    "auth.and": "and",
    "auth.privacy": "Privacy Policy",
    "auth.verify.ing": "Verifying...",
    "auth.verify.ed": "Verified",
    "auth.verify.click": "Click to verify",
    "auth.btn.login": "Log in",
    "auth.btn.register": "Sign up with Email",
    "auth.no_account": "Don't have an account?",
    "auth.has_account": "Already have an account?"
  }
};

export function ThemeLanguageProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useLocalStorage<Theme>("app-theme", "light");
  const [language, setLanguage] = useLocalStorage<Language>("app-language", "zh");

  useEffect(() => {
    const root = window.document.documentElement;
    root.classList.remove("light", "dark");
    root.classList.add(theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme((prev) => (prev === "light" ? "dark" : "light"));
  };

  const toggleLanguage = () => {
    const list: Language[] = ["zh", "ja", "en"];
    setLanguage((prev) => {
      const nextIndex = (list.indexOf(prev) + 1) % list.length;
      return list[nextIndex];
    });
  };

  const t = (key: TranslationKey) => {
    return translations[language]?.[key] || translations["zh"][key];
  };

  return (
    <ThemeLanguageContext.Provider value={{ theme, language, toggleTheme, toggleLanguage, setTheme, setLanguage, t }}>
      {children}
    </ThemeLanguageContext.Provider>
  );
}

export function useThemeLanguage() {
  const context = useContext(ThemeLanguageContext);
  if (context === undefined) {
    throw new Error("useThemeLanguage must be used within a ThemeLanguageProvider");
  }
  return context;
}
