import { createContext, useContext, useEffect, ReactNode } from "react";
import { useLocalStorage } from "../hooks/useLocalStorage";

type Language = "zh" | "ja" | "en";
type Theme = "light" | "dark";

const zhTranslations = {
  "header.title": "泛式",
  "header.blog": "更新记录",
  "header.login": "登录",
  "header.discover": "图库",
  "header.workspace": "工作台",
  "header.screening": "放映会",
  "header.games": "游戏回",
  "header.about": "关于",
  "plaza.title": "探索",
  "plaza.tab.souls": "同人",
  "plaza.tab.moments": "瞬间",
  "plaza.tab.groups": "群组",
  "plaza.search": "搜索同人...",
  "plaza.btn.search": "搜索",
  "plaza.filter.default": "默认",
  "plaza.filter.hot": "热门",
  "plaza.filter.new": "最新",
  "plaza.filter.all": "全部",
  "plaza.count": "个同人作品",
  "plaza.dev.moments": "瞬间内容开发中...",
  "plaza.dev.groups": "群组内容开发中...",
  "plaza.active": "上次活跃于 {days} 天前",
  "hero.badge": "站点功能地图",
  "hero.title.prefix": "这里整理的是",
  "hero.title.highlight1": "放映会",
  "hero.title.highlight2": "与记录",
  "hero.subtitle": "一个围绕电影动画片源、同人图库、文章记录和站主工作台搭建的个人内容站。",
  "hero.browser.title": "站点预览 — 从浏览到发布的完整流程",
  "hero.browser.status1": "实时",
  "hero.browser.status2": "在线",
  "hero.chat.msg1": "想找本周放映会和已经整理过的片源。",
  "hero.chat.msg2": "可以从放映会进入排期，也能在全量片源库里按电影、动画、杂谈和标签筛选。",
  "hero.chat.msg3": "我还想补充一个片源，站主审核后会展示吗？",
  "hero.chat.thinking": "正在同步片源投稿、文章评论和监控状态...",
  "hero.events.title": "站点动态",
  "hero.events.1": "放映会: 本周排期已更新",
  "hero.events.2": "图库: 新同人作品已归档",
  "hero.events.3": "工作台: 服务器监控运行中",
  "hero.activity.title": "内容",
  "hero.activity.memory": "监控",
  "hero.activity.item1": "最近整理",
  "hero.activity.item1.desc": "「电影 / 动画 / 杂谈」片源记录",
  "gwy.title": "从浏览到沉淀",
  "gwy.subtitle": "首页只是入口。真正的内容会在放映会、图库、文章和工作台里持续更新，访客可以浏览，登录用户可以参与，站主负责审核与发布。",
  "gwy.c1.title": "浏览内容",
  "gwy.c1.desc": "从首页快速进入放映会、图库、文章和关于页。",
  "gwy.c1.msg1": "我想先看看最近有什么放映会和新文章。",
  "gwy.c2.title": "参与投稿",
  "gwy.c2.desc": "登录后可以提交片源、留下反馈，也可以参与文章评论。",
  "gwy.c2.sys": "[系统] 收到新的片源投稿：周末动画补完计划。",
  "gwy.c2.msg1": "这个条目可以补到片源库里吗？",
  "gwy.c2.msg2": "可以。站主会在工作台审核，补全海报、分类和标签后再发布。",
  "gwy.c3.title": "站主审核",
  "gwy.c3.desc": "工作台集中处理投稿、文章、图库、放映会和网站监控。",
  "gwy.c3.msg1": "这条投稿已经补充了来源链接和说明。",
  "gwy.c3.msg2": "审核通过后会进入片源库，也可以加入后续放映会排期。",
  "gwy.c4.title": "发布沉淀",
  "gwy.c4.desc": "内容发布后会成为可检索的长期记录，图片保存在服务器本地目录。",
  "gwy.c4.sys": "工作台发布了「六月放映记录」",
  "gwy.c4.msg1": "发布后访客就能看到了吗？",
  "gwy.c4.msg2": "是的，首页入口、文章记录和放映会页面都会指向最新内容。",
  "scen.title": "这里可以",
  "scen.title2": "做什么？",
  "scen.subtitle": "四个主要入口，把内容浏览和站主管理串起来。",
  "scen.1.t": "周末放映会",
  "scen.1.d": "查看本周排期、月度记录和已归档的电影动画片源。",
  "scen.2.t": "瀑布流图库",
  "scen.2.d": "浏览同人作品和图片资料，保留海报比例和标签筛选。",
  "scen.3.t": "文章记录",
  "scen.3.d": "阅读站主发布的记录，也可以登录后参与评论。",
  "scen.4.t": "站主工作台",
  "scen.4.d": "管理内容、审核投稿、上传图片，并查看真实服务器监控。",
  "scen.r1": "放映会讨论 (4)",
  "mq.title": "功能亮点",
  "mq.subtitle": "不是商业产品介绍，而是这个站当前真正可用的内容能力。",
  "mq.1.name": "放映会",
  "mq.1.role": "片源与排期",
  "mq.1.body": "全量电影动画片源库支持分类、标签和时间线浏览，周末放映会可以沉淀为月度记录。",
  "mq.2.name": "图库",
  "mq.2.role": "同人作品",
  "mq.2.body": "图片以瀑布流展示，保留海报和作品的原始比例，也支持只看图片的沉浸浏览。",
  "mq.3.name": "文章",
  "mq.3.role": "发布与评论",
  "mq.3.body": "站主可以发布文章，访客能阅读，登录用户可以评论，内容会持续沉淀成站内记录。",
  "mq.4.name": "工作台",
  "mq.4.role": "内容管理",
  "mq.4.body": "站主在工作台处理投稿、用户、文章、图库和放映会，减少直接改文件的维护成本。",
  "mq.5.name": "监控",
  "mq.5.role": "真实状态",
  "mq.5.body": "网站监控记录访问趋势、服务器 CPU、内存、磁盘、数据库延迟和异常待办。",
  "mq.6.name": "上传",
  "mq.6.role": "本地存储",
  "mq.6.body": "图片上传会保存到服务器本地 uploads 目录，部署简单，也方便后续统一备份。",
  "faq.title": "常见问题",
  "faq.q1": "这个网站主要做什么？",
  "faq.a1": "这是一个个人内容站，用来整理放映会排期、电影动画片源、同人图库、文章记录和站点动态。首页负责说明入口，具体内容会在各个页面持续更新。",
  "faq.q2": "访客可以参与什么？",
  "faq.a2": "访客可以浏览公开内容；登录后可以提交片源、留下反馈、参与文章评论。投稿会进入工作台，由站主审核、补充信息后再发布。",
  "faq.q3": "图片上传保存在哪里？",
  "faq.a3": "当前生产环境使用服务器本地存储。图片会保存到 server/data/uploads，并通过 api.linzesss.icu/uploads 访问。后续备份服务器时需要一起备份这个目录。",
  "faq.card1.title": "深入了解",
  "faq.card1.l1": "如何提交片源和反馈",
  "faq.card1.l2": "放映会与片源库的关系",
  "faq.card1.l3": "本地上传目录与备份说明",
  "faq.card2.title": "快速入口",
  "faq.doc": "进入工作台",
  "fb.title": "站点",
  "fb.title2": "核心功能",
  "fb.subtitle": "围绕内容浏览、投稿审核、图片上传和服务器状态，把个人站维护流程集中起来。",
  "fb.1.t": "放映会片源库",
  "fb.1.d": "整理电影、动画、经典片和杂谈条目，支持排期、归档、标签和时间线查看。",
  "fb.2.t": "图库与同人作品",
  "fb.2.d": "以瀑布流展示图片，支持分类筛选、海报比例自适应和本地上传保存。",
  "fb.3.t": "文章与评论",
  "fb.3.d": "站主发布文章，用户登录后参与评论，让内容从一次更新变成长期记录。",
  "fb.4.t": "工作台与监控",
  "fb.4.d": "集中管理用户、投稿、内容发布和服务器状态，异常会进入待办区域。",
  "pr.title": "访问",
  "pr.title2": "权限",
  "pr.subtitle": "不同身份看到的内容不同，但都围绕浏览、参与和维护这个站点。",
  "pr.1.name": "访客",
  "pr.1.price": "浏览",
  "pr.1.desc": "无需登录即可查看公开页面和站点内容。",
  "pr.1.f1": "查看首页、放映会、图库和文章",
  "pr.1.f2": "浏览公开片源和月度记录",
  "pr.1.f3": "查看图片作品和标签",
  "pr.1.f4": "访问备案与公开信息",
  "pr.1.cta": "开始浏览",
  "pr.2.name": "登录用户",
  "pr.2.price": "参与",
  "pr.2.period": "",
  "pr.2.desc": "登录后可以留下内容痕迹，参与站点资料完善。",
  "pr.2.f1": "提交电影动画片源",
  "pr.2.f2": "发送反馈和补充说明",
  "pr.2.f3": "参与文章评论",
  "pr.2.f4": "保留个人提交记录",
  "pr.2.f5": "等待站主审核发布",
  "pr.2.cta": "登录参与",
  "pr.2.pop": "推荐",
  "pr.3.name": "站主 / 管理员",
  "pr.3.price": "维护",
  "pr.3.desc": "通过工作台管理内容、用户、上传和服务器状态。",
  "pr.3.f1": "审核片源投稿和反馈",
  "pr.3.f2": "发布文章与图库内容",
  "pr.3.f3": "维护放映会排期",
  "pr.3.f4": "查看访问趋势和服务器监控",
  "pr.3.f5": "确认异常待办",
  "pr.3.cta": "进入工作台",
  "footer.trusted": "个人内容站",
  "footer.partner": "放映会 / 图库 / 文章",
  "footer.anthropic": "服务器监控已启用",
  "footer.terms": "条款",
  "footer.privacy": "隐私",
  "footer.status": "系统状态: 正常",
  "auth.welcome": "欢迎回来",
  "auth.create": "创建账户",
  "auth.login.desc": "登录你的 AnySoul 账户",
  "auth.register.desc": "开始你的 AnySoul 之旅",
  "auth.google": "使用 Google 继续",
  "auth.or": "或",
  "auth.name": "姓名",
  "auth.name.placeholder": "你的姓名",
  "auth.email": "邮箱",
  "auth.email.placeholder": "you@example.com",
  "auth.password": "密码",
  "auth.password.login": "输入密码",
  "auth.password.create": "创建密码",
  "auth.password.confirm": "确认密码",
  "auth.password.confirm.placeholder": "再次输入密码",
  "auth.terms.agree": "我同意",
  "auth.terms": "服务条款",
  "auth.and": "和",
  "auth.privacy": "隐私政策",
  "auth.verify.ing": "验证中...",
  "auth.verify.ed": "已验证",
  "auth.verify.click": "点击验证",
  "auth.btn.login": "登录",
  "auth.btn.register": "邮箱注册",
  "auth.no_account": "没有账户？",
  "auth.has_account": "已有账户？"
} as const;

const supplementalTranslations = {
  zh: {
    "header.talks": "杂谈回",
    "talks.eyebrow": "Talk Archive",
    "talks.title": "杂谈回",
    "talks.subtitle": "把每周讨论、站点更新和内容线索整理成可以检索、回看和继续补充的长期记录。",
    "talks.livenow": "直播中",
    "talks.open": "打开杂谈",
    "talks.thisweek": "本周安排",
    "talks.archive": "往期归档",
    "talks.showall": "查看全部",
    "talks.recent": "近期动态",
    "talks.top": "热门文章",
    "talks.new": "新上传"
  },
  ja: {
    "header.talks": "雑談回",
    "talks.eyebrow": "Talk Archive",
    "talks.title": "雑談回",
    "talks.subtitle": "毎週の話題、サイト更新、内容の手がかりを検索・回覧できる記録として整理します。",
    "talks.livenow": "配信中",
    "talks.open": "雑談を開く",
    "talks.thisweek": "今週の予定",
    "talks.archive": "過去ログ",
    "talks.showall": "すべて見る",
    "talks.recent": "最近の更新",
    "talks.top": "人気記事",
    "talks.new": "新着アップロード"
  },
  en: {
    "header.talks": "Talks",
    "talks.eyebrow": "Talk Archive",
    "talks.title": "Talks",
    "talks.subtitle": "A searchable archive for weekly conversations, site updates, and long-running content threads.",
    "talks.livenow": "Live now",
    "talks.open": "Open talk",
    "talks.thisweek": "This Week",
    "talks.archive": "Archive",
    "talks.showall": "Show all",
    "talks.recent": "Recent",
    "talks.top": "Top Articles",
    "talks.new": "New Uploads"
  }
} as const;

type SupplementalTranslationKey = keyof typeof supplementalTranslations.zh;
export type TranslationKey = keyof typeof zhTranslations | SupplementalTranslationKey;

interface ThemeLanguageContextType {
  theme: Theme;
  language: Language;
  toggleTheme: () => void;
  toggleLanguage: () => void;
  setTheme: (theme: Theme) => void;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const ThemeLanguageContext = createContext<ThemeLanguageContextType | undefined>(undefined);

const translations: Record<Language, Partial<Record<TranslationKey, string>>> = {
  zh: zhTranslations,
  ja: {
    "header.title": "泛式",
    "header.blog": "更新履歴",
    "header.login": "ログイン",
    "header.discover": "ギャラリー",
    "header.workspace": "ワークスペース",
    "header.screening": "上映会",
    "header.games": "ゲーム実況",
    "header.about": "概要",
    "plaza.title": "探索",
    "plaza.tab.souls": "ファンアート",
    "plaza.tab.moments": "モーメント",
    "plaza.tab.groups": "グループ",
    "plaza.search": "ファンアートを検索...",
    "plaza.btn.search": "検索",
    "plaza.filter.default": "デフォルト",
    "plaza.filter.hot": "人気",
    "plaza.filter.new": "新着",
    "plaza.filter.all": "すべて",
    "plaza.count": "個のファンアート",
    "plaza.dev.moments": "モーメント機能は開発中です...",
    "plaza.dev.groups": "グループ機能は開発中です...",
    "plaza.active": "{days}日前にアクティブ",
    "hero.badge": "サイト機能マップ",
    "hero.title.prefix": "ここに整理しているのは",
    "hero.title.highlight1": "上映会",
    "hero.title.highlight2": "と記録",
    "hero.subtitle": "映画・アニメのソース、ファンアートギャラリー、記事記録、管理ワークスペースをまとめた個人サイトです。",
    "hero.browser.title": "サイトプレビュー — 閲覧から公開まで",
    "hero.browser.status1": "リアルタイム",
    "hero.browser.status2": "オンライン",
    "hero.chat.msg1": "今週の上映会と整理済みのソースを探したい。",
    "hero.chat.msg2": "上映会ページでスケジュールを確認でき、全量ライブラリでは映画・アニメ・雑談・タグで絞り込めます。",
    "hero.chat.msg3": "ソースを追加したら、管理者の確認後に公開されますか？",
    "hero.chat.thinking": "ソース投稿、記事コメント、監視状態を同期中...",
    "hero.events.title": "サイト動向",
    "hero.events.1": "上映会: 今週の予定を更新",
    "hero.events.2": "ギャラリー: 新しいファンアートを整理",
    "hero.events.3": "ワークスペース: サーバー監視が稼働中",
    "hero.activity.title": "コンテンツ",
    "hero.activity.memory": "監視",
    "hero.activity.item1": "最近の整理",
    "hero.activity.item1.desc": "「映画 / アニメ / 雑談」ソース記録",
    "gwy.title": "閲覧から蓄積へ",
    "gwy.subtitle": "ホームは入口です。上映会、ギャラリー、記事、ワークスペースで内容を継続更新し、訪問者は閲覧、ログインユーザーは参加、管理者は審査と公開を行います。",
    "gwy.c1.title": "コンテンツを見る",
    "gwy.c1.desc": "ホームから上映会、ギャラリー、記事、About へすぐ移動できます。",
    "gwy.c1.msg1": "最近の上映会と新しい記事をまず見たい。",
    "gwy.c2.title": "投稿に参加",
    "gwy.c2.desc": "ログイン後、ソース投稿、フィードバック、記事コメントに参加できます。",
    "gwy.c2.sys": "[システム] 新しいソース投稿を受信：週末アニメ補完計画。",
    "gwy.c2.msg1": "この項目をライブラリに追加できますか？",
    "gwy.c2.msg2": "できます。管理者がワークスペースで確認し、ポスター、分類、タグを補って公開します。",
    "gwy.c3.title": "管理者が審査",
    "gwy.c3.desc": "ワークスペースで投稿、記事、ギャラリー、上映会、サイト監視をまとめて処理します。",
    "gwy.c3.msg1": "この投稿に出典リンクと説明を追加しました。",
    "gwy.c3.msg2": "承認後はソースライブラリに入り、今後の上映予定にも追加できます。",
    "gwy.c4.title": "公開して蓄積",
    "gwy.c4.desc": "公開された内容は検索可能な長期記録になり、画像はサーバーのローカルディレクトリに保存されます。",
    "gwy.c4.sys": "ワークスペースが「六月上映記録」を公開しました",
    "gwy.c4.msg1": "公開後は訪問者も見られますか？",
    "gwy.c4.msg2": "はい。ホーム入口、記事記録、上映会ページから最新内容へ進めます。",
    "scen.title": "このサイトで",
    "scen.title2": "できること",
    "scen.subtitle": "四つの主要入口で、閲覧と管理をつなぎます。",
    "scen.1.t": "週末上映会",
    "scen.1.d": "今週の予定、月次記録、整理済みの映画・アニメソースを確認できます。",
    "scen.2.t": "Masonry ギャラリー",
    "scen.2.d": "ファンアートや画像資料を、比率を保ったままタグで閲覧できます。",
    "scen.3.t": "記事記録",
    "scen.3.d": "管理者の記事を読み、ログイン後はコメントにも参加できます。",
    "scen.4.t": "管理ワークスペース",
    "scen.4.d": "コンテンツ、投稿、画像アップロード、本物のサーバー監視を管理します。",
    "scen.r1": "上映会トーク (4)",
    "mq.title": "機能ハイライト",
    "mq.subtitle": "商用プロダクト紹介ではなく、今このサイトで使える機能です。",
    "mq.1.name": "上映会",
    "mq.1.role": "ソースと予定",
    "mq.1.body": "映画・アニメの全量ライブラリは分類、タグ、タイムライン表示に対応し、上映会は月次記録として蓄積できます。",
    "mq.2.name": "ギャラリー",
    "mq.2.role": "ファンアート",
    "mq.2.body": "画像は Masonry で表示し、ポスターや作品の比率を保ったまま没入的に閲覧できます。",
    "mq.3.name": "記事",
    "mq.3.role": "公開とコメント",
    "mq.3.body": "管理者が記事を公開し、ログインユーザーがコメントできるため、更新が長期記録として残ります。",
    "mq.4.name": "ワークスペース",
    "mq.4.role": "コンテンツ管理",
    "mq.4.body": "投稿、ユーザー、記事、ギャラリー、上映会を一か所で扱い、直接ファイルを触る負担を減らします。",
    "mq.5.name": "監視",
    "mq.5.role": "実ステータス",
    "mq.5.body": "アクセス傾向、CPU、メモリ、ディスク、DB 遅延、異常タスクを記録します。",
    "mq.6.name": "アップロード",
    "mq.6.role": "ローカル保存",
    "mq.6.body": "画像はサーバーの uploads ディレクトリに保存され、シンプルにデプロイとバックアップができます。",
    "faq.title": "よくある質問",
    "faq.q1": "このサイトは何をする場所ですか？",
    "faq.a1": "上映会予定、映画・アニメソース、ファンアートギャラリー、記事記録、サイト動向を整理する個人サイトです。ホームは入口で、具体的な内容は各ページで更新されます。",
    "faq.q2": "訪問者は何に参加できますか？",
    "faq.a2": "公開内容は誰でも閲覧できます。ログイン後はソース投稿、フィードバック、記事コメントに参加でき、投稿は管理者の審査後に公開されます。",
    "faq.q3": "アップロード画像はどこに保存されますか？",
    "faq.a3": "本番環境ではサーバーのローカルストレージを使います。画像は server/data/uploads に保存され、api.linzesss.icu/uploads から配信されます。",
    "faq.card1.title": "もっと知る",
    "faq.card1.l1": "ソース投稿とフィードバック",
    "faq.card1.l2": "上映会とライブラリの関係",
    "faq.card1.l3": "ローカルアップロードとバックアップ",
    "faq.card2.title": "クイック入口",
    "faq.doc": "ワークスペースへ",
    "fb.title": "サイトの",
    "fb.title2": "中心機能",
    "fb.subtitle": "閲覧、投稿審査、画像アップロード、サーバー状態をひとつの個人サイトにまとめます。",
    "fb.1.t": "上映会ソースライブラリ",
    "fb.1.d": "映画、アニメ、名作、雑談を整理し、予定、アーカイブ、タグ、タイムラインで確認できます。",
    "fb.2.t": "ギャラリーとファンアート",
    "fb.2.d": "Masonry 表示、カテゴリ絞り込み、比率自動調整、ローカルアップロード保存に対応します。",
    "fb.3.t": "記事とコメント",
    "fb.3.d": "管理者が記事を公開し、ログインユーザーがコメントして、内容を長期記録にできます。",
    "fb.4.t": "ワークスペースと監視",
    "fb.4.d": "ユーザー、投稿、公開内容、サーバー状態を管理し、異常はタスクとして表示します。",
    "pr.title": "アクセス",
    "pr.title2": "権限",
    "pr.subtitle": "閲覧、参加、管理の役割ごとに使える機能を整理しています。",
    "pr.1.name": "訪問者",
    "pr.1.price": "閲覧",
    "pr.1.desc": "ログインなしで公開ページを確認できます。",
    "pr.1.f1": "ホーム、上映会、ギャラリー、記事を見る",
    "pr.1.f2": "公開ソースと月次記録を閲覧",
    "pr.1.f3": "画像作品とタグを見る",
    "pr.1.f4": "公開情報と ICP 表示を確認",
    "pr.1.cta": "閲覧開始",
    "pr.2.name": "ログインユーザー",
    "pr.2.price": "参加",
    "pr.2.period": "",
    "pr.2.desc": "ログイン後、サイト内容の補完に参加できます。",
    "pr.2.f1": "映画・アニメソースを投稿",
    "pr.2.f2": "フィードバックを送信",
    "pr.2.f3": "記事コメントに参加",
    "pr.2.f4": "自分の投稿履歴を保持",
    "pr.2.f5": "管理者の公開審査を待つ",
    "pr.2.cta": "ログインして参加",
    "pr.2.pop": "おすすめ",
    "pr.3.name": "管理者",
    "pr.3.price": "管理",
    "pr.3.desc": "ワークスペースで内容、ユーザー、アップロード、サーバー状態を扱います。",
    "pr.3.f1": "投稿とフィードバックを審査",
    "pr.3.f2": "記事とギャラリーを公開",
    "pr.3.f3": "上映会予定を管理",
    "pr.3.f4": "アクセス傾向と監視を確認",
    "pr.3.f5": "異常タスクを確認",
    "pr.3.cta": "ワークスペースへ",
    "footer.trusted": "個人コンテンツサイト",
    "footer.partner": "上映会 / ギャラリー / 記事",
    "footer.anthropic": "サーバー監視稼働中",
    "footer.terms": "利用規約",
    "footer.privacy": "プライバシー",
    "footer.status": "システム状況: 正常",
    "auth.welcome": "お帰りなさい",
    "auth.create": "アカウント作成",
    "auth.login.desc": "AnySoulアカウントにログイン",
    "auth.register.desc": "AnySoulの旅を始めよう",
    "auth.google": "Googleで続行",
    "auth.or": "または",
    "auth.name": "名前",
    "auth.name.placeholder": "あなたの名前",
    "auth.email": "メールアドレス",
    "auth.email.placeholder": "you@example.com",
    "auth.password": "パスワード",
    "auth.password.login": "パスワードを入力",
    "auth.password.create": "パスワードを作成",
    "auth.password.confirm": "パスワードの確認",
    "auth.password.confirm.placeholder": "パスワードを再入力",
    "auth.terms.agree": "私は",
    "auth.terms": "利用規約",
    "auth.and": "および",
    "auth.privacy": "プライバシーポリシー",
    "auth.verify.ing": "検証中...",
    "auth.verify.ed": "検証済み",
    "auth.verify.click": "クリックして検証",
    "auth.btn.login": "ログイン",
    "auth.btn.register": "メールで登録",
    "auth.no_account": "アカウントがない場合",
    "auth.has_account": "アカウントがある場合"
  },
  en: {
    "header.title": "Fanshi",
    "header.blog": "Changelog",
    "header.login": "Login",
    "header.discover": "Gallery",
    "header.workspace": "Workspace",
    "header.screening": "Screenings",
    "header.games": "Gaming",
    "header.about": "About",
    "plaza.title": "Explore",
    "plaza.tab.souls": "Fanart",
    "plaza.tab.moments": "Moments",
    "plaza.tab.groups": "Groups",
    "plaza.search": "Search fanart...",
    "plaza.btn.search": "Search",
    "plaza.filter.default": "Default",
    "plaza.filter.hot": "Hot",
    "plaza.filter.new": "New",
    "plaza.filter.all": "All",
    "plaza.count": "fanart",
    "plaza.dev.moments": "Moments in development...",
    "plaza.dev.groups": "Groups in development...",
    "plaza.active": "Active {days} days ago",
    "hero.badge": "Site feature map",
    "hero.title.prefix": "This site organizes",
    "hero.title.highlight1": "Screenings",
    "hero.title.highlight2": "and Records",
    "hero.subtitle": "A personal content site for movie and anime sources, fanart gallery, article records, and the owner's workspace.",
    "hero.browser.title": "Site preview — from browsing to publishing",
    "hero.browser.status1": "Live",
    "hero.browser.status2": "Online",
    "hero.chat.msg1": "I want to find this week's screenings and organized sources.",
    "hero.chat.msg2": "Use the screenings page for schedules, or filter the full source library by movies, anime, topics, and tags.",
    "hero.chat.msg3": "If I submit a source, will it appear after owner review?",
    "hero.chat.thinking": "Syncing source submissions, article comments, and monitoring status...",
    "hero.events.title": "Site activity",
    "hero.events.1": "Screenings: this week's schedule updated",
    "hero.events.2": "Gallery: new fanart archived",
    "hero.events.3": "Workspace: server monitoring online",
    "hero.activity.title": "Content",
    "hero.activity.memory": "Monitoring",
    "hero.activity.item1": "Recently organized",
    "hero.activity.item1.desc": "\"Movie / Anime / Topic\" source records",
    "gwy.title": "From browsing to archive",
    "gwy.subtitle": "The homepage is only the entrance. Screenings, gallery, posts, and workspace keep the real content updated; visitors browse, signed-in users participate, and the owner reviews and publishes.",
    "gwy.c1.title": "Browse content",
    "gwy.c1.desc": "Jump from the homepage to screenings, gallery, posts, and about.",
    "gwy.c1.msg1": "I want to see recent screenings and new posts first.",
    "gwy.c2.title": "Contribute",
    "gwy.c2.desc": "After signing in, users can submit sources, send feedback, and comment on posts.",
    "gwy.c2.sys": "[System] New source submission received: weekend anime catch-up plan.",
    "gwy.c2.msg1": "Can this item be added to the source library?",
    "gwy.c2.msg2": "Yes. The owner reviews it in the workspace, then completes poster, category, and tags before publishing.",
    "gwy.c3.title": "Owner review",
    "gwy.c3.desc": "The workspace handles submissions, posts, gallery, screenings, and site monitoring in one place.",
    "gwy.c3.msg1": "This submission now includes source link and description.",
    "gwy.c3.msg2": "Once approved, it enters the library and can be scheduled for future screenings.",
    "gwy.c4.title": "Publish records",
    "gwy.c4.desc": "Published content becomes searchable long-term records, with uploaded images stored locally on the server.",
    "gwy.c4.sys": "Workspace published \"June screening records\"",
    "gwy.c4.msg1": "Can visitors see it after publishing?",
    "gwy.c4.msg2": "Yes. Homepage entries, posts, and screenings will all point to the newest content.",
    "scen.title": "What can this",
    "scen.title2": "site do?",
    "scen.subtitle": "Four main entrances connect public browsing with owner maintenance.",
    "scen.1.t": "Weekend screenings",
    "scen.1.d": "View this week's schedule, monthly records, and archived movie/anime sources.",
    "scen.2.t": "Masonry gallery",
    "scen.2.d": "Browse fanart and images with preserved proportions and tag filters.",
    "scen.3.t": "Post records",
    "scen.3.d": "Read owner posts and join comments after signing in.",
    "scen.4.t": "Owner workspace",
    "scen.4.d": "Manage content, review submissions, upload images, and monitor the server.",
    "scen.r1": "Screening talk (4)",
    "mq.title": "Feature Highlights",
    "mq.subtitle": "Not a commercial product pitch, but the real capabilities available on this site.",
    "mq.1.name": "Screenings",
    "mq.1.role": "Sources and schedule",
    "mq.1.body": "The movie and anime library supports categories, tags, timeline views, and monthly screening archives.",
    "mq.2.name": "Gallery",
    "mq.2.role": "Fanart",
    "mq.2.body": "Images render in masonry layout with original poster and artwork proportions preserved.",
    "mq.3.name": "Posts",
    "mq.3.role": "Publishing and comments",
    "mq.3.body": "The owner publishes posts, and signed-in users can comment so updates become long-term records.",
    "mq.4.name": "Workspace",
    "mq.4.role": "Content management",
    "mq.4.body": "Submissions, users, posts, gallery, and screenings are managed in one place instead of editing files directly.",
    "mq.5.name": "Monitoring",
    "mq.5.role": "Real status",
    "mq.5.body": "The site tracks visits, CPU, memory, disk usage, database latency, and server alerts.",
    "mq.6.name": "Uploads",
    "mq.6.role": "Local storage",
    "mq.6.body": "Uploaded images are saved to the server uploads directory, keeping deployment and backup simple.",
    "faq.title": "FAQ",
    "faq.q1": "What is this site for?",
    "faq.a1": "It is a personal content site for screening schedules, movie/anime sources, fanart gallery, article records, and site activity. The homepage explains the entrances; each page keeps the actual content updated.",
    "faq.q2": "What can visitors participate in?",
    "faq.a2": "Public content is open to visitors. After signing in, users can submit sources, send feedback, and comment on posts. Submissions are published after owner review.",
    "faq.q3": "Where are uploaded images stored?",
    "faq.a3": "Production currently uses server local storage. Images are saved under server/data/uploads and served from api.linzesss.icu/uploads.",
    "faq.card1.title": "Learn more",
    "faq.card1.l1": "Submitting sources and feedback",
    "faq.card1.l2": "How screenings and the library connect",
    "faq.card1.l3": "Local uploads and backups",
    "faq.card2.title": "Quick links",
    "faq.doc": "Open Workspace",
    "fb.title": "Site",
    "fb.title2": "Capabilities",
    "fb.subtitle": "Content browsing, submission review, image upload, and server status are organized in one personal site.",
    "fb.1.t": "Screening source library",
    "fb.1.d": "Organize movies, anime, classics, and topic entries with schedules, archives, tags, and timeline views.",
    "fb.2.t": "Gallery and fanart",
    "fb.2.d": "Browse images in masonry layout with category filters, adaptive proportions, and local upload storage.",
    "fb.3.t": "Posts and comments",
    "fb.3.d": "The owner publishes posts, while signed-in users can comment and keep updates as long-term records.",
    "fb.4.t": "Workspace and monitoring",
    "fb.4.d": "Manage users, submissions, content publishing, and server health; alerts enter the todo area.",
    "pr.title": "Access",
    "pr.title2": "Levels",
    "pr.subtitle": "Each role has a clear path: browse, participate, or maintain the site.",
    "pr.1.name": "Visitor",
    "pr.1.price": "Browse",
    "pr.1.desc": "Read public pages without signing in.",
    "pr.1.f1": "View home, screenings, gallery, and posts",
    "pr.1.f2": "Browse public sources and monthly records",
    "pr.1.f3": "View images and tags",
    "pr.1.f4": "Check public and filing information",
    "pr.1.cta": "Start browsing",
    "pr.2.name": "Signed-in user",
    "pr.2.price": "Join",
    "pr.2.period": "",
    "pr.2.desc": "Participate in improving the site's records after signing in.",
    "pr.2.f1": "Submit movie/anime sources",
    "pr.2.f2": "Send feedback and notes",
    "pr.2.f3": "Comment on posts",
    "pr.2.f4": "Keep personal submission history",
    "pr.2.f5": "Wait for owner review",
    "pr.2.cta": "Sign in to join",
    "pr.2.pop": "Recommended",
    "pr.3.name": "Owner / Admin",
    "pr.3.price": "Maintain",
    "pr.3.desc": "Use the workspace to manage content, users, uploads, and server status.",
    "pr.3.f1": "Review submissions and feedback",
    "pr.3.f2": "Publish posts and gallery items",
    "pr.3.f3": "Maintain screening schedules",
    "pr.3.f4": "View traffic and server monitoring",
    "pr.3.f5": "Acknowledge alert todos",
    "pr.3.cta": "Open Workspace",
    "footer.trusted": "PERSONAL CONTENT SITE",
    "footer.partner": "SCREENINGS / GALLERY / POSTS",
    "footer.anthropic": "SERVER MONITORING ONLINE",
    "footer.terms": "Terms",
    "footer.privacy": "Privacy",
    "footer.status": "Status: Normal",
    "auth.welcome": "Welcome back",
    "auth.create": "Create an account",
    "auth.login.desc": "Log in to your AnySoul account",
    "auth.register.desc": "Start your journey with AnySoul",
    "auth.google": "Continue with Google",
    "auth.or": "OR",
    "auth.name": "Name",
    "auth.name.placeholder": "Your name",
    "auth.email": "Email",
    "auth.email.placeholder": "you@example.com",
    "auth.password": "Password",
    "auth.password.login": "Enter password",
    "auth.password.create": "Create password",
    "auth.password.confirm": "Confirm password",
    "auth.password.confirm.placeholder": "Re-enter password",
    "auth.terms.agree": "I agree to the",
    "auth.terms": "Terms of Service",
    "auth.and": "and",
    "auth.privacy": "Privacy Policy",
    "auth.verify.ing": "Verifying...",
    "auth.verify.ed": "Verified",
    "auth.verify.click": "Click to verify",
    "auth.btn.login": "Log in",
    "auth.btn.register": "Sign up with Email",
    "auth.no_account": "Don't have an account?",
    "auth.has_account": "Already have an account?"
  }
};

export function ThemeLanguageProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useLocalStorage<Theme>("app-theme", "light");
  const [language, setLanguage] = useLocalStorage<Language>("app-language", "zh");

  useEffect(() => {
    const root = window.document.documentElement;
    root.classList.remove("light", "dark");
    root.classList.add(theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme((prev) => (prev === "light" ? "dark" : "light"));
  };

  const toggleLanguage = () => {
    const list: Language[] = ["zh", "ja", "en"];
    setLanguage((prev) => {
      const nextIndex = (list.indexOf(prev) + 1) % list.length;
      return list[nextIndex];
    });
  };

  const t = (key: TranslationKey) => {
    const supplemental = supplementalTranslations[language]?.[key as SupplementalTranslationKey]
      || supplementalTranslations.zh[key as SupplementalTranslationKey];
    return translations[language]?.[key] || translations.zh[key] || supplemental || key;
  };

  return (
    <ThemeLanguageContext.Provider value={{ theme, language, toggleTheme, toggleLanguage, setTheme, setLanguage, t }}>
      {children}
    </ThemeLanguageContext.Provider>
  );
}

export function useThemeLanguage() {
  const context = useContext(ThemeLanguageContext);
  if (context === undefined) {
    throw new Error("useThemeLanguage must be used within a ThemeLanguageProvider");
  }
  return context;
}
